apiVersion: v1
kind: Secret
metadata:
    name: s3-creds
    namespace: velero
type: Opaque
stringData:
    credentials: ENC[AES256_GCM,data:2rqVg/MS27kE8hRs2FPkvPZQctrPX9bW08/BNzkCteCJXs/IWgONmvplSw1KNmSNaN4PgQioMCMBnizM/e9zSdsi+ftiW2Qg1NXWzAhE,iv:SMPSlGcr+uz7nJGxE6FS4Xa4Sf3osqs/G/8rZy5cbDk=,tag:92wSGYW0q3hFEssnpz8+eA==,type:str]
sops:
    age:
        - recipient: age1e8fc5nkphytyt3m2cj0g4th6cxx643pthwyq6xvha28jkpy27clq8uyax7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0bG1SbUJGeEQ2Nk9ESXRG
            V3lVOGp3QkF4THFtWisrR2lQS2tiSVcrelNBCmJRb1pwRjVPZGttZHBnY1dmRWx3
            UFdjVE9TL0I3NkRmS3dBVmFyd2tIREkKLS0tIDRFNWJnaVQ1dGw5Kzc1dHBEbEQr
            MDN5QWY4ZVlVRXB3c2FBb2cyNmpmdzQK1z5G7QZdoqZ2SAt8AGhYG6xTb5rEtWzk
            huMlSuFKSQ8aonSAs1fQ9r+li7+iKbanlCLePUz9rmmkAtk6/9RJzQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-13T15:04:37Z"
    mac: ENC[AES256_GCM,data:x4ekpiNeC8LYGUPm3VZtRshf+vLNH7U1I4yM+TCMUTWBRw6DgpjfU1HOd0zgK7axBBlKDaxbdToIDfq10k7+GlJ5Ii1u37xHlHEhUsFJjXECzc/+745OcnllgQXwazxClE0hNgo6wgOxAmiVT72tHevUcafU4szLbBC1+o9nqMc=,iv:O2LH/YfCy51CeJ9twGYXUK9w7m3uTxlCH8GsmZg4BnA=,tag:4pQ4XGyWOmzbmKfWvGNdlA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
