resources:
  - ../../base/metallb
  - ../../base/cert-manager
  - ../../base/traefik
  - ../../base/rustfs
  - ../../base/openebs

patches:
  - target:
      kind: IPAddressPool
      name: traefik
    patch: |-
      - op: replace
        path: /spec/addresses
        value:
          - 192.168.1.102

  - target:
      kind: L2Advertisement
      name: traefik
    patch: |-
      - op: replace
        path: /spec/nodeSelectors/0/matchLabels/kubernetes.io~1hostname
        value: talos-llq-9ec
  - target:
      kind: L2Advertisement
      name: traefik
    patch: |-
      - op: replace
        path: /spec/interfaces
        value:
          - enp0s31f6

  - target:
      kind: StorageClass
      name: host-zfs-standard
    patch: |-
      - op: replace
        path: /parameters/poolname
        value: "tank"

  - target:
      kind: StorageClass
      name: host-zfs-files
    patch: |-
      - op: replace
        path: /parameters/poolname
        value: "tank"

  - target:
      kind: HelmRelease
      name: traefik
    patch: |-
      - op: remove
        path: /spec/values/ports

  - target:
      kind: HelmRelease
      name: traefik
    patch: |-
      - op: replace
        path: /spec/values/service/single
        value: true
  - target:
      kind: HelmRelease
      name: traefik
    patch: |-
      - op: replace
        path: /spec/values/service/annotations/loadBalancerIPs
        value: 192.168.1.102
  - target:
      kind: HelmRelease
      name: traefik
    patch: |-
      - op: replace
        path: /spec/values/ingressRoute/dashboard/matchRule
        value: Host(`traefik.rustfs.dudu.ro`)
