resources:
  - ../../base/metallb
  - ../../base/cert-manager
  - ../../base/traefik
  - ../../base/rustfs
  - ../../base/openebs

patches:
  - target:
      kind: HelmRelease
      name: traefik
    path: patches/traefik-release.yml

  - target:
      kind: L2Advertisement
      name: traefik
    path: patches/l2-advertisement.yml
  - target:
      kind: IPAddressPool
      name: traefik
    patch: |-
      - op: replace
        path: /spec/addresses
        value:
          - 192.168.1.102/32

  - target:
      kind: StorageClass
      name: host-zfs-standard
    patch: |-
      - op: replace
        path: /parameters/poolname
        value: "tank"

  - target:
      kind: StorageClass
      name: host-zfs-files
    patch: |-
      - op: replace
        path: /parameters/poolname
        value: "tank"
