apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-apikey-secret
    namespace: cert-manager
type: Opaque
stringData:
    api-token: ENC[AES256_GCM,data:VSje2DZ4vVtOqp2al6uwhokScvc0moHE0Xk9aBHqojwMTS9PddR0ew==,iv:RqYBLFzBl3/9Tf/ALFcdg1reZs6SCSQKUnmo/P8AJWA=,tag:CESIurGmTVoSy4pe9/1XwQ==,type:str]
sops:
    age:
        - recipient: age1e8fc5nkphytyt3m2cj0g4th6cxx643pthwyq6xvha28jkpy27clq8uyax7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiWUdsQzRDc0hEU2JaMGZa
            eVlXbExFZklCc0Z0WEErRGRVQ2lWK2k5QVc0CithNXVVcEdFaWYyMWp1NU1Na05Z
            OE9BS2VmaS9sMWdLUExKb1lpQWU3NkEKLS0tIE8yVXJZMDFXVEFNWnlsQjdNSGF5
            S2tJUllkSHd5cGxrZVBPS1N6bnhuUHMK0nun0S2SAoPFpOs3jAk0rdiedBSctWXo
            RegFJtmjFSe+msGbgM8g9w8ggbIl1wXw/4hjjnXM0oNFvbF92S4I/A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-13T14:17:29Z"
    mac: ENC[AES256_GCM,data:9FP8LgcMYKWl66nT0YtvWzuMWSaRh1kPoYK/whbJXjLngJWQlYhMqOQpW8eh+i5vdBN/iK0kJEj6qVndyCx4JhBeGDjzTGbKm+j2VMqhbSCM8GGsSa25QZwE/B8C20C7ckJVS0JwCydTGciAshkrBvklJGsgxW2S3AZRZ9Q0VXA=,iv:6LA5RewdehIgoEatUP9Vw5aokoImppmV3HnaPjxoYfc=,tag:82lOOV6dKNdDY5H+NJ/eKQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
