---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: adguardhome
  namespace: adguardhome
spec:
  interval: 5m
  chart:
    spec:
      chart: adguard-home
      version: 13.0.0
      sourceRef:
        kind: HelmRepository
        name: adguardhome
        namespace: adguardhome
  values:
    persistence:
      data:
        type: pvc
        accessModes: ReadWriteMany
        size: 4Gi
        storageClass: host-zfs-standard
      config:
        type: pvc
        accessModes: ReadWriteMany
        size: 100Mi
        storageClass: host-zfs-standard
    service:
      dns-tcp:
        type: LoadBalancer
        annotations:
          metallb.io/loadBalancerIPs: 192.168.1.53
      dns-udp:
        type: LoadBalancer
        annotations:
          metallb.io/loadBalancerIPs: 192.168.1.53
