apiVersion: v1
kind: Secret
metadata:
    name: domain-creds
    namespace: flux-system
type: Opaque
stringData:
    email: ENC[AES256_GCM,data:OL6LcJYkmy+VtLOH2afgAq67gHwM3Q==,iv:nU3+evqbZoTCsLcMWlucSNFQGKXr95JvUURcQ9DEUd8=,tag:QJJ3nlV9clW5z3fmpot6sg==,type:str]
    domain: ENC[AES256_GCM,data:pdmzsTPO1A==,iv:F1/NtJ4+pCXUIkt5ZLnVOEIBunHiQS4GAcuZK16RREY=,tag:293CKFxodklpMjU5+KjxBQ==,type:str]
sops:
    age:
        - recipient: age1e8fc5nkphytyt3m2cj0g4th6cxx643pthwyq6xvha28jkpy27clq8uyax7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4TUEzTlp1SjQ3dmFWTFVo
            Vyt6a3VRYmFPbnl0ZVZYdjlQS3g4QUlPZ0F3CkVVVlUwcU1mWWtoQWRwd3BjR2t1
            SlNoeFp1cnBSWGJ0eEZzYmpQbExFNjQKLS0tIFdkRS9uUlkrakkweU44K21LOEpx
            U3Urc2h4aFY2bXNES2Q2dG1XNUlySkUKj4Rh+mZLd9y3QgZIgYXAuPpIROMcRp64
            evef8f1AK5craCwgtQkqH7nBKxoTMrBDOvH/qLaZWOfjagj6UbwrTQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-13T15:02:02Z"
    mac: ENC[AES256_GCM,data:esJ2iVkXa6aJtIQhHWnb6AT6g2MspKAAAb7J09MJNLvhuIwnr3j8Y12jPEIJwMGmfnqgNlg1/hCQOyjIjIP++9xM/Odwxgy/G4dpeuJR/nbmX5ofTQglG/mGd6nKsxB2wblBqF8uAkO3yDTcdH3Ofnxyl8nAqJgOOm2LWL7Hw8g=,iv:6RNkf9NrcBEAlW2Xwb5BwGwSn+G2wAjK5ub5ehKKVwU=,tag:dp5AFR+iaIMbfTHrg2rMdQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
