---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: sftpgo
  namespace: sftpgo
spec:
  interval: 5m
  chart:
    spec:
      chart: sftpgo
      version: 9.18.0
      sourceRef:
        kind: HelmRepository
        name: sftpgo
        namespace: sftpgo
  values:
    fallbackDefaults:
      storageClass: host-zfs-files
    persistence:
      backupdirectory:
        enabled: true
        type: pvc
        accessModes: ReadWriteMany
        size: 500Gi
      configpath:
        enabled: true
        type: pvc
        size: 500Mi
      data:
        enabled: true
        type: pvc
        retain: true
        accessModes: ReadWriteMany
        size: 500Gi
      shareaccess:
        enabled: true
        type: pvc
        accessModes: ReadWriteMany
        size: 100Gi
