apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: radicale
  namespace: radicale
spec:
  storageClassName: host-zfs-files
  resources:
    requests:
      storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
