apiVersion: v1
kind: Secret
metadata:
    name: radicale-creds
    namespace: flux-system
type: Opaque
stringData:
    radicale_username: ENC[AES256_GCM,data:6JUpyZ48,iv:W+UNCdGw8Ba36MvQKsjbhmSuDiR0m7IAEKcDwuRXme0=,tag:CFEsQgSrCliICRRxoYOH3Q==,type:str]
    radicale_password: ENC[AES256_GCM,data:Lw7SvQEHN33vTfm8vjjsRIdU/Ec=,iv:n4vkTKK3LYjv38ha3oaSN1bUUNRpk2GNv0Fdo7ZzWjg=,tag:DCCbCdKOoCVUwzcPHh8xyQ==,type:str]
sops:
    age:
        - recipient: age1e8fc5nkphytyt3m2cj0g4th6cxx643pthwyq6xvha28jkpy27clq8uyax7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwTVRhMVlLaDJHS1ExRkJn
            QzF1UEczQzJLbVlFckdxMjJxbVF4NkNYeWc4CnVhVmNmOCtUQklLRjFlTTJaRFNG
            bXI4NzNrcThjM0JXNksxNm13SytTNk0KLS0tIG5SY0N2WkljM2xpVHpnaUxiR2ho
            SVQ2YTVnYThmbUYraGVCOXlWUFhNclUKdEZ5NbzFZP1I6kzfeyfm0IJqdbEgNvt2
            Pmkc005iJdkQ5w6+W6FZIQ30dMqjs0qw3fhWyywGmIwvF4qQxFFVwQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-13T15:05:26Z"
    mac: ENC[AES256_GCM,data:gQ6I9cFNbX0GVJjYXyciCzvPVkDwNkSWZ9v/00vPNZk3H/7MFJf+KUxpUddWCmrS31aY7q91Go427xbs9uD74JmVTbLBAM/keO1C6NSIdn+atf4ovqtGqxYcYn9Tm7+q5YqmZM5HL3nI/jEHq36gZUcMRWI/wmuEjFlTb2mbR5o=,iv:c9GHa+H1kNoPbpGDbxTp/mgCtiLWt3/OejVa1irKo18=,tag:sE9L9iXszN1iBtgKvOA+yg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
