---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: radicale
  namespace: radicale
spec:
  interval: 5m
  chart:
    spec:
      chart: radicale
      version: 8.17.2
      sourceRef:
        kind: HelmRepository
        name: radicale
        namespace: radicale
  values:
    persistence:
      data:
        enabled: true
        type: pvc
        retain: true
        accessModes: ReadWriteMany
        size: 2Gi
        storageClass: host-zfs-files

    # ingress:
    #   radicale:
    #     enabled: true
    #     primary: true
    #     ingressClassName: traefik
    #     targetSelector:
    #       radicale: 80
    #     integrations:
    #       traefik:
    #         enabled: true
    #         entrypoints:
    #           - web
