resources:
  - ../../base/openebs
  - ../../base/cnpg
  - ../../base/traefik
  - ../../base/metallb
  - ../../base/cert-manager
  - ../../base/adguardhome
  - ../../base/velero
  - ../../base/external-dns

patches:
  - target:
      kind: HelmRelease
      name: traefik
    path: patches/traefik-release.yml
