apiVersion: v1
kind: Secret
metadata:
    name: adguard-configuration
    namespace: external-dns
type: Opaque
stringData:
    url: ENC[AES256_GCM,data:kmtmB6ogh3MnooGeCjplHrsFXe92iRJQlHgXhO8PgfKMoDEBYAu+lJJvo1lHKNug2vuOCROxmJADuv93atCWZdZIdg==,iv:CRDJBxueQgT0KKUnih7MSpGliSYZLhNe5yLCz4cil5Q=,tag:xsnIdouG4DjRyHUu2yXUBQ==,type:str]
    user: ENC[AES256_GCM,data:ovfCtlfJ,iv:h0jellJh3k2SZkmqvz6wTGtnjaRGlgZEoOgfqSJGxkY=,tag:7QY04SUu1BUfqrK0jFT0ZA==,type:str]
    password: ENC[AES256_GCM,data:j9SXF7STgeLdFK7eOMJDGqsl,iv:694bh0pqpdK1Gx0Yk5qsWZhVxrmwIkChew7tPkU4dC8=,tag:WLKFtKWXT7B9fs28p5vzYA==,type:str]
sops:
    age:
        - recipient: age1e8fc5nkphytyt3m2cj0g4th6cxx643pthwyq6xvha28jkpy27clq8uyax7
          enc: |
              -----BEGIN AGE ENCRYPTED FILE-----
              YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHYTYvbVNPeGRYWGNLeDd6
              YmhKRjFMSHZuN2tYOXRWNHRFQ0o2OUNQS0VrCk45d1NVcklaM0MwQ2p3WXBkZGtB
              OXhEQ0pBY3lpUHA0TE1BekxhMXFxVTQKLS0tIGNXR2I2Um5pNGZWRGJyVU1XM2sw
              Qm5rSzdkbW5mdERuQ3UxUmN1VlRETDQKdY3ijPFZUjFD8y5raJROy2km3dE3bNua
              URVMXU3aTTeKNhiXsrn8shQIl5wi/n6rKnvJEu02V9MfM0u+aqYiZw==
              -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-13T15:02:16Z"
    mac: ENC[AES256_GCM,data:ezyA7207+QHG4LbRdI/HzO1rhqm3O25ZkQWEzHe8NFLCtE624VRIm80w/wt/R5MsG41KcyHk3VoBbgfy6tXhD9GYFix4gfZ8fOjFnlsQnSWLEu71auqkDynGK6QTT/D3bA+qDx8I7enUnYvaCXU6m5jlOyMyVQ420KreJBAFhHw=,iv:mjRVktecXy1jXnjeRgw8yQMQ9oL0ayBQjplYEaoEEn4=,tag:kAK48ZI9ke9Wt2IKqIx/oQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
