---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: homepage-route
  namespace: traefik
  annotations:
    external-dns.alpha.kubernetes.io/target: 192.168.1.196
    kubernetes.io/ingress.class: traefik
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`home.${domain}`)
      services:
        - kind: Service
          name: homepage
          namespace: homepage
          port: 5232
  tls:
    secretName: wildcard-certificate-secret
