---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: immich-cluster
  namespace: immich
spec:
  interval: 5m
  chart:
    spec:
      chart: cluster
      version: ">= 0.5.0"
      sourceRef:
        kind: HelmRepository
        name: cnpg
        namespace: cnpg-system
  values:
    cluster:
      instances: 1
      imageName: ghcr.io/tensorchord/cloudnative-pgvecto.rs:16-v0.3.0
      storage:
        size: 8Gi
        storageClass: host-zfs-standard
      postgresql:
        shared_preload_libraries:
          - "vchord.so"
      initdb:
        database: immich
        owner: immich
        postInitApplicationSQL:
          # Commands based on: https://immich.app/docs/administration/postgres-standalone/#without-superuser-permission
          - CREATE EXTENSION vchord CASCADE;
          - CREATE EXTENSION earthdistance CASCADE;
      roles:
        - name: immich
          ensure: present
          login: true
          superuser: true
